routes/web.php
<?php
use App\Model\Post;
use App\Model\User;
use App\Http\Resources\PostResource;
use App\Http\Resources\UserResource;
/*
|-----------------
---------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
		return view('welcome');
	});
Route::get('/lang/{locale}', function ($locale) {
	App::setLocale($locale);
	return view('welcome');
	});

Auth::routes();

Route::middleware(['auth'])->group(function () {

Route::get('/home', 'HomeController@index')->name('home');

// Route::resource('posts','PostController');
// Route::resource('category','CategoryController');
Route::resource('commends','CommendController');


});

resources/views/Category.blade.php
@extends('layouts.app')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tagsinput/0.8.0/bootstrap-tagsinput.css" />
  <script src="http://demo.itsolutionstuff.com/plugin/jquery.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tagsinput/0.8.0/bootstrap-tagsinput.js"></script>
@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <h1 class="panel-success">Category Lists</h1>
        
        		</div>
        	</div>
        </div>
 @foreach($category as $items)
        <div class="panel" style="width: 400px;margin-bottom: 1px;">
            <div class="panel">
                 <div style="text-align: center;">
                 	<div class="panel panel-default">
                     	  <div class="col-md-6">
                              Category Id: <h6 for="user" class="control-label custom">{{ $items->id }}</h6>
                          </div>
                          <div class="col-md-6">
                             Category Name:<h6 for="user" class="control-label custom">{{ $items->name }}</h6>
                          </div>
                      <a href="{{route('category.show',['id' => $items->id])}}"> 
                          <button type="submit" name="view" class="btn btn-info">
                              View post
                          </button>
                      </a>
            
                 	</div>
                 </div>
            </div>
      
        </div>
 @endforeach
@endsection

resources/views/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">POSTS</div>
        
        {!! Form::model($post,['route' => ['posts.update', $post->id]]) !!}
            <input type="hidden" name="_method" value="PUT">
    
                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif
                    
                        <div class="form-group">
                            <label for="user" class="col-md-4 control-label">Post title</label>

                            <div class="col-md-6">
                                <input type="text" value="{{$post->post_title}}" class="form-control" name="post_title" required>
                            </div>
                        </div>
                         <div class="form-group">
                            <label for="user" class="col-md-4 control-label">Post Descreption</label>

                            <div class="col-md-6">
                                <input type="text" value="{{$post->descreption}}" class="form-control" name="descreption" required>
                            </div>
                       
                       <div class="form-group">
                        <label for="user" class="col-md-4 control-label">category</label>
                        <div class="col-md-6">
                      
                      {!! Form::select('categories',$categories); !!} 
      
                            </div>
                       </div>
                        </div>
                        <input type="submit" name="update" value="Update Post" class="btn btn-primary">  
                                    
                      
           {!! Form::close() !!}
                </div>




            </div>
        </div>
    </div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
              <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                          
                        </div>
                    @endif
            </div>
      <div class="col-md-8 col-md-offset-2">
          <div class="panel panel-default">
              {{-- <div style="-webkit-border-after-style: inset;">Welcome User: {{Auth::user()->name}}</div> --}}
              {{-- <div style="-webkit-border-after-style: inset;" >Email: {{Auth::user()->email}}</div> --}}
             
        
           You are logged in!
         
          </div>

        
            <a href="posts/create">
                <button type="button" class="btn btn-primary">
                            Add Posts
                </button>
            </a>
        </br>
        </br>

        @foreach($posts as $items)
        <div class="panel panel-success">
            <div class="panel-heading panel-input">
                <div class="col-md-8">
                    <h2 for="user" class="control-label custom">{{ $items->post_title }}</h2>
                </div>
                <div class="col-md-8">
                <h6 for="user" class="control-label custom">{{ $items->descreption }}</h6>
                </div>

                  <div class="col-md-4" style="float: right;">
                    <h6 for="user" class=" control-label custom"> posted on:{{ $items->created_at }}</h6>
                    <h6 for="user" class=" control-label custom"> Category id:{{ $items->category_id }}</h6>
                    <h6 for="user" class=" control-label custom"> User id:{{ $items->user_id }}</h6>
                   </div>
                    

                  <div class="col-md-2" style="margin-top: 25px;">
                     <a href="{{route('posts.edit',['id' => $items->id])}}">  
                        <button class="btn-primary btn" type="submit">
                           Edit
                        </button>
                    </a>
                  </div>
                  <div class="col-md-2" style="margin-top: 25px;">
                     <a href="{{route('posts.show',['id' => $items->id])}}">  
                        <button class="btn-info btn" type="button">View</button>
                    </a>
                  </div>
                 
                  <div class="col-md-2" style="margin-top: 25px;">
                    <form action="{{url('posts', [$items->id])}}" method="POST">
                        {{method_field('DELETE')}}
                        {{csrf_field()}}
                        <button class="btn-danger btn" type="submit">
                            Delete
                        </button>
                    </form>
                  </div>
            
                
              
                </div>
            </div>
              @endforeach
        </div>
    </div>
</div>

@endsection

resources/views/posts.blade.php
@extends('layouts.app')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tagsinput/0.8.0/bootstrap-tagsinput.css" />
    <script src="http://demo.itsolutionstuff.com/plugin/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tagsinput/0.8.0/bootstrap-tagsinput.js"></script>
@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                POSTS
                </br></br>
    @foreach($errors->all() as $message) 
    {{ $message }} </br>
      @endforeach
              </div>        
        {!! Form::open(['route' => 'posts.store','files'=>true]) !!}
                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif
         
                        <div class="form-group">
                            <label for="user" class="col-md-4 control-label">Post title</label>

                            <div class="col-md-6">
                              {!! Form::text('title',null,['class'=>'form-control','placeholder'=>'Enter Title'])!!}
                            </div>
                        </div>
                         <div class="form-group" style="margin-top: 40px">
                            <label for="user" class="col-md-4 control-label">Post Descreption</label>

                            <div class="col-md-6">
                        {!! Form::text('descreption',null,['class'=>'form-control','placeholder'=>'Enter Descreption'])!!}
                            </div>
                        </div>  
                       
                       <div class="form-group" style="margin-top: 40px">
                        <label for="user" class="col-md-4 control-label">category</label>
                        <div class="col-md-6">
                           @if($categories)
                              
                                {!! Form::select('categories', $categories); !!}
                            @endif
                        </div>
                       </div>
                           <br/><br/></br>
                       <div class="form-group" >
                              <label for="user" class="col-md-4 control-label">Tags:</label>
                         <div class="col-md-6">
                            <select data-role="tagsinput" type="text" multiple="multiple" name="tags[]" placeholder="Enter Tags" >
                            </select>
                        </div>
                      </div>  
            
              <div class="form-group">
                  <label for="user" class="col-md-4 control-label">Image Upload:</label>
                  <div class="row">
                      <div class="col-md-6">
                          {!! Form::file('image', array('class' => 'form-control')) !!}
                      </div>
                  </div>     
              </div>
                       <div class="col-md-6" style="margin-top: 40px">
                        <input type="submit" name="add" value="Add Post" class="btn btn-primary">  
                          </div>          
                      
           {!! Form::close() !!}
                </div>




            </div>
        </div>
    </div>
</div>
@endsection

resources/views/view_category_post.blade.php
@extends('layouts.app')

@section('content')

<h2 style="text-align:center"><b>{{$category->name}}</b> Category Wise Posts Listing: </h2>

@foreach($posts as $items)
  <div class="card">

    <h1>{{$items->post_title}}</h1>
    <p class="title" style="text-align: left;">User:{{Auth::user()->name}}</p>
    <p>{{$items->descreption}}</p>
    <div style="margin: 24px 0;">
      <a href="#"><i class="fa fa-dribbble"></i></a> 
      <a href="#"><i class="fa fa-twitter"></i></a>  
      <a href="#"><i class="fa fa-linkedin"></i></a>  
      <a href="#"><i class="fa fa-facebook"></i></a> 
   </div>
   <label>Tags:</label>
   <div>
   <a href="">
<div class="tags"> 
abcd
</div></a>
</div>
  </div>

@endforeach
<p><a class="a1" href="{{ url('/category')}}"><button class="button1">Back</button></p></p>

@endsection

resources/views/view_post.blade.php
@extends('layouts.app')
 <script src="http://demo.itsolutionstuff.com/plugin/jquery.js"></script>
@section('content')
{{-- Heading post --}}


<div class="container">
        <div class="row">
            <div class="col-md-8 ">
               <div class="panel panel-default">
                 <h2 class="panel panel-success">View Post</h1>
        
        	   </div>
        	</div>
        </div>

{{-- Post view container --}}

 <div class="panel panel-success">
    <div class="panel-heading panel-input"  style="height: 300px;">
        <div class="col-md-8">
            <label>User name:</label><div >{{Auth::user()->name}}</div>
            <label>User Email:</label><div>{{Auth::user()->email}}</div>
        </div>
        <div class="col-md-8">
            <h2 for="user" class="control-label custom">{{ $post->post_title }}</h2>
        </div>
        <div class="col-md-8">
            <h6 for="user" class="control-label custom">{{ $post->descreption }}</h6>
        </div>

<img src="data:image/{{$post->post_image_type}};base64,{{base64_encode($post->post_image)}}" alt="image not found" style="width: 150px;height: 150px;">
        <div class="col-md-4" style="float: right;">
            <h6 for="user" class=" control-label custom"> posted on:{{ $post->created_at }}</h6>
            <h6 for="user" class=" control-label custom"> Category id:{{ $post->category_id }}</h6>
            <h6 for="user" class=" control-label custom"> User id:{{ $post->user_id }}</h6>
        </div>
      <div class="col-md-4" style="margin-top: 50px">
        @foreach($tags as $tag)
        <a style="font-size: 25px" href="">#{{$tag}}</a>
        @endforeach
      </div>

    </div>
</div>

    
{{-- Commend Box --}}

    <div class="container">
       {!! Form::open(['route' => 'commends.store']) !!}
       {!! Form::textarea('commends', null, ['size' => '30x4','class'=>'cust', 'placeholder'=>'Write somthing you wish', 'required']); !!}
       <input type="hidden" name="id" value="{{$post->id}}">
       </br>
        {{session()->put('key', $post->id)}}
        {{ Form::submit('Save', array('class' => 'btn btn-primary')) }}
        {!! Form::close() !!}
    </div>


{{-- Commends by lists --}}

    @foreach($commends as $items)
     {!! Form::model($commends,['route' => ['commends.update', $items->id]]) !!}
        <div class="container">
           <div class="panel panel-info" style="text-align:inherit;">
                <a><b>{{Auth::user()->name}}</b></a> 
                @if (session('edit'))
                <input type="text" name="updatecmd" value="{{$items->descreption}}" />
                @else
                <p>{{$items->descreption}} </p>
                @endif
                <label>{{$items->created_at}}</label>


            <div class="" class="btn-primary btn" style="margin-top: 25px;float: right;">
       
            @if (session('edit'))
          
          {{-- update commend  --}}

               
                <input type="hidden" name="_method" value="PUT">                 
                      <button class="btn" type="submit">update commend</button>
                      
                      
                {!! Form::close() !!}
                @else
                <a href="{{route('commends.edit',['id' => $items->id])}}">edit commend</a> 
           @endif
            </div>

{{-- Delete commend link --}}

             {!! Form::open(['method' => 'DELETE', 
                'route' => ['commends.destroy', $items->id], 
                'id' => 'form-delete-commends-' . $items->id]) !!}
                <a href="" class="data-delete" 
                  data-form="commends-{{ $items->id }}">
                  delete</a>
              {!! Form::close() !!}
           </div>
        </div>
@endforeach

{{-- Scripts for deleteing commend by using link(href) --}}

<script>
$(function () {
  $('.data-delete').on('click', function (e) {
    if (!confirm('Are you sure you want to delete?')) return;
    e.preventDefault();
    $('#form-delete-' + $(this).data('form')).submit();
  });
});

</script>

@endsection